[package]
name = "nft-app-data-deploy"
version = "1.0.0"
authors = ["Juan Obligado"]
edition = "2018"

[dependencies]
deadpool-postgres = "0.9.0"
env_logger = "^0.8"
log = "^0.4"
tokio-postgres = "^0.7"
tokio-postgres-migration = "^0.1"